user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

cms:
    resource: "@CmsBundle/Resources/config/routing.yml"
    prefix:   /cms/

back_office:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /back/

front_office:
    resource: "@FrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

connexion: 
    path:     /login
    defaults: { _controller: FOSUserBundle:Security:login }
    