<?php

namespace FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
	public function myFindAll(){
		$qb = $this->createQueryBuilder('a');
		$qb->orderBy('a.date' , 'DESC');
		return $qb->getQuery()->getResult();
	}
}
